### ISSUE TITLE
Array not yet dim'd

### ISSUE THREAD

**Issue by sikosis** [AmiBlitz/AmiBlitz3#71] opened 2022-11-09 02:45 UTC
`fmt$ = "%ld ($%lx)" + Chr$(10)`

Affected source: Chr$(10)

The above code fails to compile with that error about not being dim'd.

**Comment by honitos** [comment] 2022-11-09 08:01
I can not reproduce this behaviour.
Is the function Chr$() tokenized, that means is it printed as bold ?
If not, the compiler did not recognize Chr$() as a function probably because not blitzlibs have been loaded.

Please open the instruction browser, all loaded libs will be displayed there.
Chr$() is part of the "stringfunclib".

**Comment by T0lk13n** [comment] 2022-11-12 23:20
Cant test in the A1200 but under MorphOS it works correctly.

**Comment by mbergmann-sh** [comment] 2023-02-17 08:44
This might happen if you forgot a closing bracket or use a call to function/statement with round brackets instead of curly brackets.

**Closed** 2023-02-17 15:57 UTC
Labels: investigation, non reproducable
