### ISSUE TITLE
Lockup Loading... anything into the editor

### ISSUE THREAD

**Issue by DisasterIncarnate** [AmiBlitz/AmiBlitz3#60] opened 2022-09-28 22:32 UTC
Using an unpatched/basic/clean OS3.1 and a patched OS3.2.1 on FS-UAE and WinUAE

Any and every version of AmiBlitz3 above 3.8.1 causes my entire system to lock up when loading any project, be that an AB3 file or even a plain text file with a single word in it.

I am currently stuck on 3.8.1 as this is the last and only version that can actually load my projects without locking/freezing up the entire system, Snoopdos shows nothing of note as the editor does load up fine, the menus all work etc/etc, it just all dies horribly when trying to load any of my projects and snoopdos doesnt get time to save any reasons for the lockup....due to well, locking up.

I have tried every version above 3.8.1 and they all have the same behaviour, I thought it was perhaps OS3.2.x or my patches which is why i made a basic/clean OS3.1 that is totally vanilla and i get the same behaviour.

Any thought/ideas/potential fixes I could try would be appreciated.

**Comment by honitos** [comment] 2022-09-29 13:32
@DisasterIncarnate :Do the included examples work`?
Could you provied me a simple example source file ?

**Comment by DisasterIncarnate** [comment] 2022-09-30 04:22
Everything locks up the system instantly, nothing gets to load, just immediate lockup after selecting a file, i can load a .txt file containing the word "hello" and it still all locks up, an example isnt really needed.

Here is a quick yt vid showing the issue, note this same behaviour happens on any of my installs/os versions, be they clean or patched up, same behaviour if entering amiblitz manually from cli with boot sequence disabled to ensure no patches/hacks are interfering.

https://www.youtube.com/watch?v=m_yokjmpdSs

I have no such issues with 3.8.1 which is the last version to work correctly for me so this has got me stumped atm.

**Comment by honitos** [comment] 2022-10-11 08:30
Ok i can confirm the crash when loading a textfile without the file extension ".ab3"
But loading a file with that extension works as the problem is lofqted in the code that handles "other" file types.

So loading your sources should work if they have that extension.

Schöne Grüße,
Sven Dröge
________________________________

**Comment by DisasterIncarnate** [comment] 2022-10-11 11:44
i'll give that a try, i did move to plain old .txt files as i was getting error messages (_something about comdata_) on compile which magically went away when i used .txt.

**Comment by DisasterIncarnate** [comment] 2022-10-12 10:48
ok, you are correct, the newer AmiBlitz3 versions do load their own example source codes without crashing, loading any of my 3.8.1 code locks the newer versions up.

here is a link to something i was recently just making/playing around with which ofc locks up everything above 3.8.1, was/is/will be a program simply to list all my prefs programs in SYS:Prefs and house them in 1 listview in a window which can launch them with a double click, isnt finished yet, not even sure if i need it but its something to play around with, and ofc it does lock up the editor in newer AmiBlitz 3's

https://file.io/ZO5ljRI9oHZn

**Comment by DisasterIncarnate** [comment] 2022-10-12 13:15
Quick update, given you said there was an issue with the loader, i tried something different, i went into 3.8.1, loaded the AB3 program in the link above, selected all the text in the project, went to Workbench and opened TextEdit, pasted the code into there, and saved the project as ALL-PREFS.TXT.

I then rebooted, loaded AmiBlitz3.9 and instead of loading the TXT file in, i loaded up TextEdit, loaded in my ALL-PREFS.TXT, selected all and copied the text, then went into the Amiblitz3.9 editor and pasted the text in, the program would compile and run, i can edit the code, all seems well, so i then saved it as an AB3 file, which worked.

However at this point, I am back to the old issue, with this "clean" new save as AB3, the editor again locks up with this freshly made AB3 file if i try and load it the regular way.  The example still work but this fresh made AB3 locks everything up again.

**Comment by honitos** [comment] 2022-10-25 07:23
fixed with upcoming version

**Closed by honitos** 2022-10-25 07:23 UTC
Labels: investigation
