### ISSUE TITLE
Find function crashes (3.9.10b2)

### ISSUE THREAD

**Issue by daedalus2097** [AmiBlitz/AmiBlitz3#92] opened 2024-03-25 22:44 UTC
More often than not (~75% of the time), the Find function crashes with a $8000002B guru. Fresh install of the 3.9.10b2 release, loading a single source file and running a search. It doesn't seem to make a difference whether the search term is present in the source or not, or whether the search is forwards or backwards.

**Comment by honitos** [comment] 2024-09-16 08:29
@daedalus2097: I cannot reproduce the crash. Can you tell me infos about your configuration (CPU,FPU,RAM,OS)?

**Comment by daedalus2097** [comment] 2024-09-16 19:46
Hey :) It was running under WinUAE, OS 3.9, '030 + FPU, 128MB RAM and RTG.
It wasn't 100% reproducible, but typically happens when you search for a
term that doesn't exist in the source code.

Thanks,
    Rob

**Comment by honitos** [comment] 2024-09-17 13:22
Thanks for the infos. I found and fixed several enforcer hits. One of them was within the find function.
Maybe that was the cause. I am going to release a new beta version soon.

BTW: how many lines does the source code have where you are seeing the crashes?

**Comment by daedalus2097** [comment] 2024-09-19 20:10
Good news :) I tried a couple of different files, both around 1,000-2,000
lines.

**Comment by honitos** [comment] 2024-10-15 13:01
ok, will be in the release within the next days.

**Closed by honitos** 2024-10-15 13:01 UTC
Labels: investigation
